spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:8885
          predicates:
            - Path= /Enseignants/**

        - id: r2
          uri: http://localhost:8882
          predicates:
            - Path= /Chercheurs/**

        - id: r3
          uri: http://localhost:8884
          predicates:
            - Path= /Projets/**

rsa:
  public-key: classpath:Keys/publicKey.pem